import Link from "next/link";
import GuideLayout from "@/app/components/guides/GuideLayout";
import { getDreamHref } from "@/lib/routes";
import DreamCompassPageCTA from "@/components/DreamCompassPageCTA";

export default function ClusterGuidePage({ clusterGuide }) {
  const hasEditorialGroups = clusterGuide.groups?.length > 0;
  const toc = [{ id: "how-to-read", title: "How to read these dreams" }, { id: "connected-dreams", title: "Find your dream" }, ...(clusterGuide.reflectionQuestions?.length ? [{ id: "reflection", title: "Reflect on the dream" }] : []), { id: "perspectives", title: "Perspectives and limits" }, { id: "related-pathways", title: "Related pathways" }];
  const guide = { ...clusterGuide, category: "Dream Pattern Guide", sections: toc.map((item) => ({ title: item.title, id: item.id })) };
  const readingWords = [clusterGuide.intro, clusterGuide.editorialAnchor, clusterGuide.frameworkNote, clusterGuide.compassPrompt, ...(clusterGuide.principles || []).flatMap((item) => [item.title, item.body]), ...(clusterGuide.groups || []).flatMap((group) => [group.title, group.description, ...(group.dreams || []).flatMap((dream) => [dream.title, dream.microSummary || dream.summary || dream.description])]), ...(clusterGuide.reflectionQuestions || []), ...(clusterGuide.relatedPathways || []).flatMap((item) => [item.title, item.description])].filter(Boolean).join(" ").trim().split(/\s+/).length;
  const readingTime = Math.max(3, Math.ceil(readingWords / 200));
  return <GuideLayout guide={guide} toc={toc} readingTime={readingTime} relatedDreams={[]} relatedGuides={[]} continueReading={false}>
    <section aria-label="Introduction" className="space-y-5"><p className="text-lg leading-9 text-[#4F4A44]">{clusterGuide.intro}</p>{clusterGuide.editorialAnchor && <p className="border-l-2 border-[#B79B5E] pl-5 text-base leading-8 text-[#625C55]">{clusterGuide.editorialAnchor}</p>}</section>
    <section id="how-to-read" className="scroll-mt-24 border-t border-[#E2DCD3] pt-12"><h2 className="mb-7 font-serif text-3xl md:text-4xl">How to read these dreams</h2><div className="grid gap-5 md:grid-cols-2">{clusterGuide.principles.map((item)=><article key={item.title} className="rounded-2xl border border-[#E2DCD3] bg-white p-6"><h3 className="font-serif text-xl">{item.title}</h3><p className="mt-3 leading-7 text-[#625C55]">{item.body}</p></article>)}</div></section>
    <section id="connected-dreams" className="scroll-mt-24 border-t border-[#E2DCD3] pt-12"><h2 className="mb-3 font-serif text-3xl text-[#1A1A1A] md:text-4xl">Find the experience that matches</h2><p className="mb-8 max-w-2xl leading-7 text-[#625C55]">Choose the pathway that reflects what actually happened. Shared imagery alone does not make two dreams equivalent.</p>{hasEditorialGroups ? <div className="space-y-12">{clusterGuide.groups.map((group)=><section key={group.title}><h3 className="font-serif text-2xl">{group.title}</h3><p className="mb-5 mt-2 max-w-2xl text-sm leading-6 text-[#6B6B6B]">{group.description}</p><div className="grid gap-4 sm:grid-cols-2">{group.dreams.map((dream)=><Link key={dream.slug} href={getDreamHref(dream)} className="rounded-2xl border border-[#E2DCD3] bg-white p-5 hover:border-[#B79B5E]"><h4 className="font-serif text-xl">{dream.title}</h4><p className="mt-2 line-clamp-3 text-sm leading-6 text-[#6B6B6B]">{dream.microSummary || dream.summary || dream.description}</p></Link>)}</div></section>)}</div> : <div className="grid gap-4 sm:grid-cols-2">{clusterGuide.dreams.map((dream) => <Link key={dream.slug} href={getDreamHref(dream)} className="rounded-2xl border border-[#E2DCD3] bg-white p-5 hover:border-[#B79B5E]"><h3 className="font-serif text-xl">{dream.title}</h3><p className="mt-2 text-sm leading-6 text-[#6B6B6B]">{dream.microSummary || dream.summary || dream.description}</p></Link>)}</div>}</section>
    {clusterGuide.reflectionQuestions?.length > 0 && <section id="reflection" className="scroll-mt-24 border-t border-[#E2DCD3] pt-12"><h2 className="mb-4 font-serif text-3xl md:text-4xl">Reflect on what happened</h2><p className="mb-6 leading-7 text-[#625C55]">These questions are prompts for context, not a diagnosis or test.</p><ul className="space-y-4">{clusterGuide.reflectionQuestions.map((question) => <li key={question} className="flex gap-3 rounded-xl bg-white p-4 leading-7 text-[#5F574E]"><span aria-hidden="true" className="text-[#B79B5E]">—</span><span>{question}</span></li>)}</ul></section>}
    <section id="perspectives" className="scroll-mt-24 border-t border-[#E2DCD3] pt-12"><h2 className="mb-5 font-serif text-3xl md:text-4xl">Perspectives and limits</h2><p className="text-lg leading-8 text-[#5F574E]">{clusterGuide.frameworkNote}</p><div className="mt-7 flex flex-wrap gap-3">{clusterGuide.emotionalPatterns.map((pattern) => <span key={pattern} className="rounded-full border bg-white px-4 py-2 text-sm">{pattern}</span>)}</div></section>
    <section id="related-pathways" className="scroll-mt-24 border-t border-[#E2DCD3] pt-12"><h2 className="mb-6 font-serif text-3xl text-[#1A1A1A] md:text-4xl">Continue with context</h2><div className="grid gap-4 md:grid-cols-2">{clusterGuide.relatedPathways.map((pathway) => <Link key={pathway.href} href={pathway.href} className="rounded-2xl border bg-white p-5 hover:border-[#B79B5E]"><h3 className="font-serif text-xl">{pathway.title}</h3>{pathway.description && <p className="mt-2 text-sm leading-6 text-[#6B6B6B]">{pathway.description}</p>}</Link>)}</div></section>
    <section className="border-t border-[#E2DCD3] pt-12"><p className="mb-5 max-w-2xl leading-7 text-[#625C55]">{clusterGuide.compassPrompt}</p><DreamCompassPageCTA dreamTitle={clusterGuide.title} /></section>
  </GuideLayout>;
}
