create table if not exists public.dream_compass_feedback (
  id bigint generated by default as identity primary key,
  feedback_token uuid not null unique,
  rating smallint not null check (rating between 1 and 5),
  comment text check (comment is null or char_length(comment) <= 1000),
  result_slug text check (
    result_slug is null
    or result_slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'
  ),
  created_at timestamptz not null default now()
);

alter table public.dream_compass_feedback enable row level security;

revoke all on table public.dream_compass_feedback from anon, authenticated;
revoke all on sequence public.dream_compass_feedback_id_seq from anon, authenticated;

create index if not exists dream_compass_feedback_created_at_idx
  on public.dream_compass_feedback (created_at desc);

create index if not exists dream_compass_feedback_rating_idx
  on public.dream_compass_feedback (rating);

comment on table public.dream_compass_feedback is
  'Anonymous, one-per-Compass-run ratings and optional comments submitted after results.';

comment on column public.dream_compass_feedback.feedback_token is
  'Anonymous browser-generated identifier used only to prevent duplicate feedback for one Compass run.';

comment on column public.dream_compass_feedback.result_slug is
  'Closest-matching DreamScriptures reading shown when feedback was submitted.';
